fix: and use
Milly0120/siro pull request #3
Opened 2021-03-31 04:18 UTC by hands8142

2021-03-31 19:04 UTC, CwhiteKJ approved these changes

2021-03-31 19:09 UTC, CwhiteKJ requested changes
I think it could be replaced in the following way.
```js
if(isNaN(args[0]) || (args[0] > 100 || args[0] < 1)) { /* ... */ }
```

This way, lines 14 and 15 are not needed.

2021-03-31 19:11 UTC, CwhiteKJ commented
Also, the title of Pull Request doesn't match the revision. @hands8142

2021-04-01 08:56 UTC, Milly0120 approved these changes

2021-04-01 08:56 UTC, merged